"""LangGraph State Machine — orchestrates the 4-agent interview workflow."""

import operator
from typing import Annotated, TypedDict

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

from agents.planner import planner_node
from agents.interviewer import interviewer_node
from agents.evaluator import evaluator_node
from agents.coach import coach_node
import warnings
warnings.filterwarnings("ignore", module="transformers")

# ─── State Definition ───────────────────────────────────────────
class AgentState(TypedDict):
    """Full state tracked across the interview session."""

    # Chat history — uses add_messages reducer to merge, not overwrite
    messages: Annotated[list[BaseMessage], add_messages]

    # Candidate profile (free-text role, background, focus area)
    candidate_info: dict

    # Tracks how many Q&A turns have occurred
    turn_count: int

    # Accumulates evaluation results (one per turn) — uses operator.add to append
    evaluations: Annotated[list[dict], operator.add]

    # JSON plan generated by the Planner (dynamically tailored to the role)
    interview_plan: dict

    # RAG-retrieved context
    rag_context: str

    # Current phase: planning → interviewing → completed
    current_phase: str


# ─── Routing Logic ──────────────────────────────────────────────
def route_after_eval(state: AgentState) -> str:
    """Conditional edge: after evaluation, decide what happens next.

    - If turn_count >= planned turns → go to Coach for final feedback
    - Otherwise → loop back to Interviewer for the next question
    """
    turn_count = state.get("turn_count", 0)
    interview_plan = state.get("interview_plan", {})
    max_turns = interview_plan.get("num_turns", 6)

    if turn_count >= max_turns:
        return "coach"
    return "interviewer"


# ─── Graph Construction ────────────────────────────────────────
def build_graph() -> StateGraph:
    """Build and compile the LangGraph state machine.

    Flow:
        START → planner → interviewer → [user input] → evaluator → router
                                                                     ├→ interviewer (loop)
                                                                     └→ coach → END
    """
    graph = StateGraph(AgentState)

    # Add the 4 agent nodes
    graph.add_node("planner", planner_node)
    graph.add_node("interviewer", interviewer_node)
    graph.add_node("evaluator", evaluator_node)
    graph.add_node("coach", coach_node)

    # Wire the edges
    graph.add_edge(START, "planner")  # Start with planning
    graph.add_edge("planner", "interviewer")  # Plan → first question
    # NOTE: interviewer → evaluator happens AFTER user input (managed by Streamlit)
    graph.add_conditional_edges(
        "evaluator",
        route_after_eval,
        {"interviewer": "interviewer", "coach": "coach"},
    )
    graph.add_edge("coach", END)  # Coach ends the session
    with open("graph.mmd", "w") as f:
        f.write(graph.get_graph().draw_mermaid())
    return graph


def compile_graph():
    """Compile the graph for execution. Returns a runnable."""
    graph = build_graph()
    app = graph.compile()

    with open("graph.mmd", "w") as f:
        f.write(app.get_graph().draw_mermaid())
    return app
